# Generated by Django 5.0.4 on 2024-04-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('telegram_payment_charge_id', models.UUIDField()),
                ('provider_payment_charge_id', models.UUIDField()),
                ('shipping_option', models.TextField()),
                ('contact_name', models.TextField()),
                ('contact_phone_number', models.TextField()),
                ('shipping_state', models.TextField()),
                ('shipping_city', models.TextField()),
                ('shipping_street_line1', models.TextField()),
                ('shipping_street_line2', models.TextField()),
                ('shipping_post_code', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оплаченное',
                'verbose_name_plural': 'Оплаченные',
            },
        ),
        migrations.RemoveField(
            model_name='basket',
            name='order_number',
        ),
        migrations.AddField(
            model_name='basket',
            name='paidorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.paidorder'),
        ),
    ]
