# Generated by Django 5.0.4 on 2024-04-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sub_category_name',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='sub_category_name',
        ),
        migrations.AddField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='base.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='sub_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='base.subcategories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='name',
            field=models.CharField(db_index=True, default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
