# Generated by Django 5.0.4 on 2024-04-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_paidorder_remove_basket_order_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='paidorder',
            new_name='paid_order',
        ),
    ]
