# Generated by Django 5.0.4 on 2024-04-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_items_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimages',
            name='Tg_id',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
