# Generated by Django 5.0.4 on 2024-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_paidorder_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='delivery_place',
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='provider_payment_charge_id',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='telegram_payment_charge_id',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
