# Generated by Django 5.0.4 on 2024-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_mailings_photo_subcategories_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name': 'Подкатегории', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterField(
            model_name='uploadimages',
            name='Tg_id',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
