# Generated by Django 5.0.4 on 2024-05-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_basket_delivery_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidorder',
            options={'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордера'},
        ),
    ]
