# Generated by Django 5.0.4 on 2024-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_subcategories_options_alter_uploadimages_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimages',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
