# Generated by Django 5.0.4 on 2024-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_paidorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
