# Generated by Django 5.0.4 on 2024-04-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_uploadimages_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimages',
            name='name',
        ),
    ]
