# Generated by Django 5.0.4 on 2024-04-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_uploadimages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos')),
            ],
            options={
                'verbose_name': 'Баннеры',
                'verbose_name_plural': 'Баннер',
            },
        ),
        migrations.AlterModelOptions(
            name='mailings',
            options={'verbose_name': 'Рассылки', 'verbose_name_plural': 'Рассылка'},
        ),
    ]
