# Generated by Django 5.0.4 on 2024-04-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_mailings_mailling_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_code',
            new_name='articul',
        ),
    ]
