# Generated by Django 5.0.4 on 2024-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_banners_photo_tg_id_items_photo_tg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
