# Generated by Django 5.0.4 on 2024-04-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.FloatField(),
        ),
    ]
