# Generated by Django 5.0.4 on 2024-04-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_basket_order_number_alter_items_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
