# Generated by Django 5.0.4 on 2024-04-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_sub_category_items_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImages',
        ),
    ]
