# Generated by Django 5.0.4 on 2024-04-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_uploadimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='delivery_place',
            field=models.TextField(null=True),
        ),
    ]
