# Generated by Django 5.0.4 on 2024-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_basket_paid_alter_basket_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
