FROM nginx:1.19.0-alpine

SHELL ["/bin/bash", "-c"]
COPY ./default.conf /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d
# COPY proxy_params /etc/nginx
